# Generated by Django 4.2.4 on 2023-08-04 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_pet_traits"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pet",
            old_name="traits",
            new_name="trait",
        ),
    ]
