# Generated by Django 4.2.4 on 2023-08-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0002_remove_trait_pet"),
        ("pets", "0003_rename_traits_pet_trait"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="trait",
            field=models.ManyToManyField(related_name="pets", to="traits.trait"),
        ),
    ]
