# Generated by Django 4.2.4 on 2023-08-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0002_remove_trait_pet"),
        ("pets", "0005_rename_trait_pet_traits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(related_name="traits", to="traits.trait"),
        ),
    ]
